include:
  - '$CI_SERVER_URL/export/gitlab-ci/raw/master/ssh.yml'
  - template: Security/Secret-Detection.gitlab-ci.yml

stages:
  - test
  - deploy

deploy:
  stage: deploy
  image: $CI_REGISTRY/docker/ansible
  environment:
    name: staging
  script:
    - ssh_run "$DEPLOY_USER" "$DEPLOY_SERVER" "$SSH_PRIVATE_KEY" "docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY"
    - "eval $(ssh-agent -s)"
    - "echo \"$SSH_PRIVATE_KEY\"| tr -d '\r' | ssh-add -"
    - "echo \"$DEPLOY_SERVER\" > hosts"
    - "ansible-playbook -e 'ansible_python_interpreter=/usr/bin/python3' --ssh-extra-args \"-o StrictHostKeyChecking=no\" -u \"$DEPLOY_USER\" -i hosts deploy.yml"
  tags:
    - docker
    - tomsk
  only:
    - master
