global:
  scrape_interval:     15s
  evaluation_interval: 15s

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'docker-host-alpha'


# A scrape configuration containing exactly one endpoint to scrape.
scrape_configs:

  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'restservice'
    scrape_interval: 10s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['restservice:8080']

  - job_name: 'postgresql'
    scrape_interval: 10s
    static_configs:
      - targets: ['postgres_exporter:9187']

  - job_name: 'reportservice'
    scrape_interval: 10s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['reportservice:8080']
  
  - job_name: 'frontend'
    scrape_interval: 10s
    static_configs:
      - targets: ['nginx_exporter:9113']

